### ISSUE TITLE
Setting Window.DataContext Problem

### ISSUE THREAD

**Issue by yanniqq** [MarkWithall/worlds-simplest-csharp-wpf-mvvm-example#5] opened 2017-09-18 09:40 UTC
When mindlessly following your [MVVM tutorial](http://www.markwithall.com/programming/2013/03/01/worlds-simplest-csharp-wpf-mvvm-example.html) an error occurs when trying to add the Window.DataContext

Even though the window has a reference to the right namespace and the filenames are spelled correctly, VS shows an error that :"The name Presenter does not exist in the namespace {insert namespace name}"

The solution was compiling the project first without the DataContext tags. (Found in [SO comment](https://stackoverflow.com/a/27282653) Afterwards the Presenter class could be found and set as DataContext.

**Comment by MarkWithall** [comment] 2017-09-18 11:29
That's quite interesting. I occasionally have problems like this when the ViewModel classes haven't been compiled yet but that seems to be fixed by compiling without having to remove anything first.

Which version of Visual Studio/.NET/etc. are you using?

I have the Resharper plugin installed. It's possible that that is silently fixing the problem for me. I'll try it with Resharper turned off and see if I can reproduce the issue.

**Comment by yanniqq** [comment] 2017-09-18 11:45
-I was using Visual Studio Professional 2013
-.Net 4.6
-Today is Monday
-It was raining when I observed the strange behaviour
-No ReSharper was used

**Comment by MarkWithall** [comment] 2017-09-18 11:52
Thanks. I'll try it out on a selection of days of the week and weather scenarios just to be safe.

**Comment by MarkWithall** [comment] 2018-02-15 08:34
I've finally gotten around to looking at this issue in more detail. It does appear that ReSharper was hiding the problem from me and I've updated the article accordingly. Thanks for pointing it out.

**Closed as completed by MarkWithall** 2018-02-15 08:34 UTC
